default: &default
  adapter: postgresql
  encoding: unicode
  username: training
  password: <%= Rails.application.credentials.dig(Rails.env.to_sym, :pg, :password) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #раскомментировать при деплое:
  # host: localhost

development:
  <<: *default
  database: training_development

production:
  <<: *default
  database: training_production
